#!/usr/bin/env perl
# ci-scripts/lib/getVersion.pm is symlinked to ci-scripts/getVersion
# This is needed to make this script both a module and a script.
package getVersion;
use strict;
use warnings;

use base 'Exporter';
our $VERSION = '1.00';
our @EXPORT = qw(getVersion);
our @EXPORT_OK = qw(getVersionCode);

use File::Basename 'dirname';
use lib File::Basename::dirname(__FILE__) . '/lib';
use fileParser 'grepSingleLine';
use pathResolver 'getAbsolutePath';

my $scriptsDir = pathResolver::getAbsolutePath(File::Basename::dirname(__FILE__));
my $rootDir = File::Basename::dirname($scriptsDir);

sub getVersion {
    my ($version) = fileParser::grepSingleLine(
        pathResolver::getAbsolutePath($rootDir . '/build.gradle'),
        qr/^version\s*=\s*["'](\d+\.\d+\.\d+)["']$/
    );
    return $version;
}

sub getVersionCode {
    my ($versionCode) = fileParser::grepSingleLine(
        pathResolver::getAbsolutePath($rootDir . '/lib/build.gradle'),
        qr/versionCode\s+(\d+)\s*$/
    );
    return $versionCode;
}

if (not caller()) {
    print getVersion(), "\n";
}

1;
