# unprivilegedBuild.yml - v1.1
# https://github.com/ViliusSutkus89/Sample_Android_Library-MavenCentral-Instrumented_Tests/blob/master/.github/workflows/unprivilegedBuild.yml

name: unprivilegedBuild
on:
  workflow_dispatch:
  push:
# @TODO: reenable after checking
#    branches-ignore: [ master, main ]
    paths-ignore:
      - '**.md'
      - '.github/workflows/manualVersionIncrement*.yml'
      - '.github/workflows/privilegedBuild.yml'

permissions:
  actions: none
  checks: none
  contents: none
  deployments: none
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  build:
    environment: BuildUnprivileged
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 8
      - uses: android-actions/setup-android@v2

      - run: ./gradlew build

      - uses: actions/upload-artifact@v2
        with:
          name: library-lint-report.html
          path: lib/build/reports/lint-results.html

      - run: ./gradlew publishToMavenLocal
      - uses: actions/upload-artifact@v2
        with:
          name: maven-local
          path: ~/.m2

  buildSampleApp:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 8
      - uses: android-actions/setup-android@v2

      - uses: actions/download-artifact@v2
        with:
          name: maven-local
          path: ~/.m2

      - name: Prepare sample app for staging repository
        run: ./ci-scripts/prepareSampleAppForStagingRepository sampleapp app --output=build/sampleapp-staging --repository=mavenLocal

      - name: Build sample app from staging library
        run: ./gradlew build
        working-directory: build/sampleapp-staging

      - uses: actions/upload-artifact@v2
        with:
          name: sampleapp-staging-apks
          path: build/sampleapp-staging/app/build/outputs/apk/**/*.apk

      - uses: actions/upload-artifact@v2
        with:
          name: sampleapp-lint-report.html
          path: build/sampleapp-staging/app/build/reports/lint-results.html

  runInstrumentedTests:
    needs: build
    environment: BuildUnprivileged
    # Only macos VMs are available with exposed CPU extensions to run hardware accelerated emulator
    runs-on: macos-10.15
    strategy:
      fail-fast: false
      matrix:
        # Run on first and last available version on each supported arch
        # x86-android-16, x86-android-30
        # x86_64-android-21 , x86_64-android-31
        api-level: [16, 21, 30, 31]
        arch: [x86]
        target: [default]
        include:
          - api-level: 21
            arch: x86_64
          - api-level: 31
            arch: x86_64
            target: google_apis
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 8
      - uses: android-actions/setup-android@v2

      - uses: actions/download-artifact@v2
        with:
          name: maven-local
          path: ~/.m2

      - name: Prepare library to run instrumented tests on staging library
        run: ./ci-scripts/prepareLibraryTestsForStagingRepository lib --output=build/lib-staging --repository=mavenLocal

      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: ${{ matrix.arch }}
          target: ${{ matrix.target }}
          script: ./gradlew connectedCheck
          working-directory: build/lib-staging

      - uses: actions/upload-artifact@v2
        with:
          name: instrumentedTestsReport-${{ matrix.api-level }}-${{ matrix.arch }}
          path: build/lib-staging/lib/build/reports/androidTests/connected
